vadoc-public-website-redesign/Controllers/OffenderDataSurfaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using vadoc_public_website_redesign.Models;

namespace vadoc_public_website_redesign.Controllers
{
    public class OffenderDataSurfaceController : SurfaceController
    {
        private string offenderLocatorRoute = "/public-resources/offender-locator/";
        private const string PARTIAL_VIEW_FOLDER = "~/Views/Partials/OffenderLocator/";
        // Get Offenders
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GetOffenders(OffenderSearchModel model)
        {
            TempData.Clear();
            TempData["FirstName"] = model.FirstNameLowercase;
            TempData["LastName"] = model.LastNameLowercase;
            TempData["MiddleName"] = model.MiddleNameLowercase;
            TempData["OffenderId"] = model.OffenderId;
            TempData["Alias"] = model.Alias;

            // Add form submission errors to TempData
            TempData.Add("SearchErrors", new List<string>());
            if (ModelState.IsValid)
            {
                List<Offender> offenderResults = OffenderSearch(model);
                if (offenderResults.Count < 1 || offenderResults == null)
                {

                    string message = "No offender match was found using the information which was provided";
                    ((List<string>)TempData["SearchErrors"]).Add(message);
                }
                else
                {
                    TempData["SearchErrors"] = null;
                    TempData.Add("OffenderSearchResults", offenderResults);
                }
            } else
            {
                TempData["SearchErrors"] = null;
            }

            // Action for Ajax form submission
            if (Request.IsAjaxRequest())
            {

                TempData["Js"] = true;
                //return PartialView($"{PARTIAL_VIEW_FOLDER}{partialPath}");
                return PartialView($"{PARTIAL_VIEW_FOLDER}OffenderLocatorForm.cshtml", model);
            }
            else
            {
                TempData["Js"] = false;
                return Redirect($"{offenderLocatorRoute}#offender-search-results");
            }
        }

        OffenderRepository OffenderRepo = new OffenderRepository();

        public List<Offender> OffenderSearch(OffenderSearchModel offender)
        {
            List<Offender> results = new List<Offender>();

            if (ModelState.IsValid && offender.OffenderId != null)
            {
                results = GetById(offender.OffenderId);
            }
            else if (!string.IsNullOrEmpty(offender.FirstNameLowercase) && !string.IsNullOrEmpty(offender.LastNameLowercase))
            {
                results = GetByFirstAndLastName(offender.FirstNameLowercase, offender.LastNameLowercase);
            }
            else
            {
                results = BadQuery();
            }

            var filteredResults = FilterByOptional(
                results,
                offender.MiddleNameLowercase,
                offender.ReleaseDate,
                offender.AgeFrom,
                offender.AgeTo,
                offender.Race,
                offender.Gender);

            return filteredResults;
        }


        public List<Offender> GetById(int? id)
        {
            return OffenderRepo.OffenderList.Where(item => item.OffenderId == id).ToList();
        }


        public List<Offender> GetByFirstAndLastName(string firstname, string lastname)
        {
            return OffenderRepo.OffenderList.Where(x => x.FirstNameLowercase.StartsWith(firstname) && x.LastNameLowercase == lastname).ToList();
        }


        private List<Offender> FilterByOptional(
            List<Offender> results,
            string middleName = null,
            string releaseDate = null,
            int? ageFrom = null,
            int? ageTo = 99,
            string race = null,
            string gender = null
        )
        {
            if (!string.IsNullOrEmpty(middleName))
            {
                results = results.Where(x => CalculateSimilarity(x.MiddleNameLowercase, middleName) > 0.6).ToList();
            }
            if (releaseDate != null && releaseDate != "")
            {
                results = results.Where(x => x.ProjectedReleaseDate == releaseDate).ToList();
            }
            if (ageFrom != null)
            {
                results = results.Where(x => x.Age >= ageFrom && x.Age <= ageTo).ToList();
            }
            if (!string.IsNullOrEmpty(race))
            {
                results = results.Where(x => x.Race.ToLower() == race).ToList();
            }
            if (!string.IsNullOrEmpty(gender))
            {
                results = results.Where(x => x.Gender.ToLower() == gender).ToList();
            }
            return results;
        }
        public List<Offender> BadQuery()
        {
            var offenders = new List<Offender>();
            return offenders;
        }

        public double CalculateSimilarity(string source, string target)
        {
            if ((source == null) || (target == null)) return 0.0;
            if ((source.Length == 0) || (target.Length == 0)) return 0.0;
            if (source == target) return 1.0;

            int stepsToSame = ComputeLevenshteinDistance(source, target);
            return (1.0 - ((double)stepsToSame / (double)Math.Max(source.Length, target.Length)));
        }
        public int ComputeLevenshteinDistance(string source, string target)
        {
            if ((source == null) || (target == null)) return 0;
            if ((source.Length == 0) || (target.Length == 0)) return 0;
            if (source == target) return source.Length;

            int sourceWordCount = source.Length;
            int targetWordCount = target.Length;

            // Step 1
            if (sourceWordCount == 0)
                return targetWordCount;

            if (targetWordCount == 0)
                return sourceWordCount;

            int[,] distance = new int[sourceWordCount + 1, targetWordCount + 1];

            // Step 2
            for (int i = 0; i <= sourceWordCount; distance[i, 0] = i++) ;
            for (int j = 0; j <= targetWordCount; distance[0, j] = j++) ;

            for (int i = 1; i <= sourceWordCount; i++)
            {
                for (int j = 1; j <= targetWordCount; j++)
                {
                    // Step 3
                    int cost = (target[j - 1] == source[i - 1]) ? 0 : 1;

                    // Step 4
                    distance[i, j] = Math.Min(Math.Min(distance[i - 1, j] + 1, distance[i, j - 1] + 1), distance[i - 1, j - 1] + cost);
                }
            }

            return distance[sourceWordCount, targetWordCount];
        }

    }
}

vadoc-public-website-redesign/Controllers/PublicResourcesSurfaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using vadoc_public_website_redesign.Models;

namespace vadoc_public_website_redesign.Controllers
{
    public class PublicResourcesSurfaceController : SurfaceController
    {
        private const string MAIN_VIEW_FOLDER = "~/Views/";
        private const string PARTIAL_VIEW_FOLDER = "~/Views/Partials/OffenderLocator/";
        // GET: Offender Locator Page
        public ActionResult RenderOffenderLocatorPage()
        {
            return Redirect("/public-resources/offender-locator");
        }
        public ActionResult RenderOffenderLocatorForm()
        {
            return PartialView($"{PARTIAL_VIEW_FOLDER}OffenderLocatorForm.cshtml");
        }

        public ActionResult RenderOffenderSearchResults()
        {
            return PartialView($"{PARTIAL_VIEW_FOLDER}OffenderSearchResults.cshtml");
        }

        public ActionResult RenderOffenderSearchNoResults()
        {
            return PartialView($"{PARTIAL_VIEW_FOLDER}OffenderSearchNoResults.cshtml");
        }
    }
}

vadoc-public-website-redesign/Views/Partials/OffenderLocator/OffenderLocatorForm.cshtml
@inherits UmbracoViewPage<vadoc_public_website_redesign.Models.OffenderSearchModel>
@{
    Html.EnableClientValidation();
    Html.EnableUnobtrusiveJavaScript();
}

@using Umbraco.Web.Mvc;

@using (Ajax.BeginForm("GetOffenders", "OffenderDataSurface", null, new AjaxOptions
{
    HttpMethod = "POST",
    InsertionMode = InsertionMode.Replace,
    UpdateTargetId = "offender-search",
    OnSuccess = "searchSuccess",
    LoadingElementId = "loading-indicator"

}, new { autocomplete = "off", @Id = "offender-locator-form" }))
{
    @Html.AntiForgeryToken()
    if (TempData["ModelErrors"] != null)
    {
        var errors = (List<string>)TempData["ModelErrors"];
    }

    <!-- Offender Locator Form fields  -->
    <fieldset id="required-fields">
        <legend class="accessibility-hidden">A first and last name or an offender I.D. number is required</legend>
        <div class="content-wrapper">
            <h2>Required Information</h2>

            <input id="clear-form" class="link-style" type="reset" value="Clear Form">

            <label class="col-9 mar-r-1" for="first-name">
                <span class="label">First Name</span>
                @Html.TextBoxFor(x => x.FirstNameLowercase, new { @Id = "first-name", @Class = "validate", name = "first-name", data_validate = "name", @Value = TempData["FirstName"] })
                @Html.ValidationMessageFor(x => x.FirstNameLowercase)
            </label>
            <label class="col-8" for="last-name">
                <span class="label">Last Name</span>
                @Html.TextBoxFor(x => x.LastNameLowercase, new { @Id = "last-name", @Class = "validate", name = "last-name", data_validate = "name", @Value = TempData["LastName"] })
                @Html.ValidationMessageFor(x => x.LastNameLowercase)
            </label>

            <div id="or-divider-wrap">
                <div class="vertical-line"></div>
                <p class="or-divider">or</p>
                <div class="vertical-line"></div>
            </div>
            <label class="col-9" for="offender-id">
                <span class="label">Offender I.D. #</span>
                @Html.TextBoxFor(x => x.OffenderId, new { @Id = "offender-id", @Class = "validate", name = "offender-id", @Value = TempData["OffenderId"] })
                @Html.ValidationMessageFor(x => x.OffenderId)
            </label>
            <button class="primary-button submit-form" type="submit">Locate</button>
            <label id="show-optional-offender-info" for="show-optional">Show more search options</label>
        </div>
    </fieldset>
    <input class="conditional-trigger" type="checkbox" name="show-optional" id="show-optional">
    <fieldset class="conditional-fields" id="optional-fields">
        <legend class="accessibility-hidden">The following form fields are optional.</legend>
        <div class="content-wrapper clear-fix">
            <h2>Optional Information</h2>
            <label class="col-9 mar-r-1" for="middle-name">
                <span class="label">Middle Name</span>
                @Html.TextBoxFor(x => x.MiddleNameLowercase, new { @Id = "middle-name", @Class = "validate", name = "middle-name", data_validate = "name", @Value = TempData["MiddleName"] })
            </label>
            <label class="col-9 mar-r-1" for="alias">
                <span class="label">Alias</span>
                @Html.TextBoxFor(x => x.Alias, new { @Id = "alias", @Class = "validate", name = "alias", data_validate = "name", @Value = TempData["Alias"] })
            </label>
            <label class="col-9" for="location">
                <span class="label">Location</span>
                <select name="location" id="location">
                    <option value="" disabled selected>blank</option>
                    <option value="">virginia womens correctional center</option>
                    <option value="">location option</option>
                    <option value="">location option</option>
                </select>
            </label>
            <div class="offender-input-group col-9 mar-r-1">
                <label class="date-picker wrapping-label" for="release-date">
                    <span class="label">Release Date</span>
                    @Html.TextBoxFor(x => x.ReleaseDate, new { @Id = "release-date", name = "release-date", @Class = "has-datepicker validate", placeholder = "dd/mm/yyyy", data_validate = "date" })
                    <img class="calendar-icon" src="/images/global/icons/calendar.svg" aria-hidden="true">
                    @Html.ValidationMessageFor(x => x.ReleaseDate)
                </label>
            </div>
            <label class="col-4 mar-r-1" for="age-from">
                <span class="label">Age From</span>
                @Html.EditorFor(x => x.AgeFrom, new { htmlAttributes = new { @type = "number", @min = "18", @max = "100", @step = "1", @value = TempData["AgeFrom"], @id = "age-from", name = "age-from" } })
                @Html.ValidationMessageFor(x => x.AgeFrom)
            </label>
            <label class="col-4 mar-r-1" for="age-to">
                <span class="label">Age To</span>
                @Html.EditorFor(x => x.AgeTo, new { htmlAttributes = new { @type = "number", @min = "18", @max = "100", @step = "1", @value = TempData["AgeTo"], @id = "age-to", name = "age-to" } })
                @Html.ValidationMessageFor(x => x.AgeTo)
            </label>
            <label class="col-4 mar-r-1" for="sex">
                <span class="label">Sex</span>
                @Html.DropDownListFor(x => x.Gender, new SelectList(new string[] { "", "male", "female" }, TempData["Gender"]), new { @Id = "sex", name = "sex" })
            </label>
            <label class="col-4" for="race">
                <span class="label">Race</span>
                @Html.DropDownListFor(x => x.Race, new SelectList(new string[] { "", "American Indian or Alaskan Native", "Asian or Pacific Islander", "Black", "White" }, TempData["Race"]), new { @Id = "race", name = "race" })
            </label>
            <button class="primary-button submit-form" type="submit">Locate</button>
            <hr />
        </div>
    </fieldset>
}


@if (TempData["OffenderSearchResults"] != null)
{
    <div id="offender-search-results" class="content-wrapper">
        @{
            Html.RenderAction("RenderOffenderSearchResults", "PublicResourcesSurface");
        }
    </div>
}
else if (TempData["SearchErrors"] != null)
{
    <div id="offender-search-results" class="content-wrapper">
        @{
            Html.RenderAction("RenderOffenderSearchNoResults", "PublicResourcesSurface");
        }
    </div>
}

<!-- Loading Indicator -->
    @Html.Partial("SiteLayout/LoadingIndicator")
<!-- Disclaimer -->
<div class="content-wrapper">
    <div id="disclaimer">
        <h2>Disclaimer</h2>
        <p>The release date shown in the offender locator are approximations and may not display the most updated information. If you have questions or concerns regarding release dates, please refer to the Time <a href="">Computation section</a>.</p>
    </div>
</div>

vadoc-public-website-redesign/Views/Partials/OffenderLocator/OffenderSearchNoResults.cshtml
<div id="err-display" class="no-offender-results">
    <p class="body-bold">
        <img src="/images/global/icons/declined.svg"
             aria-hidden="true"
             alt="" />
        @foreach (var err in TempData["SearchErrors"] as List<string>)
        {
            <span id="search-err-message">@err</span>
        }
    </p>
    <p id="search-err-disclaimer"></p>
</div>

vadoc-public-website-redesign/Views/Partials/OffenderLocator/OffenderSearchResults.cshtml
<div id="results-sort" class="button-group">
    <h2>Search Results</h2>
    <p class="button-group-title">Sort by: </p>
    <ul>
        <li>
            <button class="active" id="name-sort"><span class="accessibility-hidden">Sort results by</span>Name</button>
        </li>
        <li>
            <button id="location-sort"><span class="accessibility-hidden">Sort results by</span>Location</button>
        </li>
        <li>
            <button id="date-sort"><span class="accessibility-hidden">Sort results by</span>Release Date</button>
        </li>
    </ul>
</div>
<ul id="result-cards">
    @foreach (var offender in TempData["OffenderSearchResults"] as IEnumerable
    <vadoc_public_website_redesign.Models.Offender>
        )
    {
        <li class="result">
            <input type="checkbox" class="conditional-trigger" id="card-flip-trigger-@offender.OffenderId" name="card-flip-trigger-@offender.OffenderId" />
            <ul class="result-data clear-fix">
                <label class="front-card-flip" for="card-flip-trigger-@offender.OffenderId">
                    <div></div>
                </label>
                <li class="result-subgroup col-7 mar-r-1 mar-l-1">
                    <dl>
                        <dt class="personal-info">Personal Information</dt>
                        <dd class="h2-style name card-front">@offender.FullName</dd>
                        <dt class="alias-label card-back">Alias:&nbsp;</dt>
                        <dd class="alias card-back">
                            <p>N/A</p>
                        </dd>
                        <dt class="accessibility-hidden">Age/Race/Sex</dt>
                        <dd class="ars"><p>@offender.Age/@offender.Race/@offender.Gender</p></dd>
                    </dl>
                </li>
                <li class="result-subgroup col-4 card-front">
                    <dl>
                        <dt>Offender I.D.#</dt>
                        <dd class="h2-style">@offender.OffenderId</dd>
                    </dl>
                </li>
                <li class="result-subgroup col-6 mar-r-1 card-front location-subgroup">
                    <dl>
                        <dt>Location</dt>
                        <dd class="h2-style multiline-heading location">@offender.LocationName</dd>
                    </dl>
                </li>
                <li class="result-subgroup col-4 mar-r-1 card-back">
                    <dl>
                        <dt>Release Date</dt>
                        <dd class="h2-style date">@(string.IsNullOrEmpty(offender.ProjectedReleaseDate) ? "N/A" : offender.ProjectedReleaseDate)</dd>
                    </dl>
                </li>
                <li class="result-subgroup col-3 card-back">
                    <dl>
                        <dt class="accessibility-hidden">J-Pay send funds to this offender</dt>
                        <dd class="result-jpay">
                            <div class="tooltip">
                                <h2>JPay</h2>
                                <p>Send funds to offender</p>
                            </div>
                            <a href="#">
                                <img src="~/images/public-resources/j-pay.svg" class="card-icon" alt="j-pay icon" />
                                <span>Send Money</span>
                            </a>
                        </dd>
                        <dt class="accessibility-hidden">Offender Visitation</dt>
                        <dd class="result-offender-page">
                            <div class="tooltip">
                                <p>See offender's location on a map</p>
                            </div>
                            <a href="#">
                                <img src="~/images/public-resources/visit.svg" class="card-icon" alt="offender visitation icon" />
                                <span> Apply to Visit</span>
                            </a>
                        </dd>
                    </dl>
                </li>
            </ul>
        </li>

    }
</ul>