vadoc-public-website-redesign/Controllers/ContactUsSurfaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using vadoc_public_website_redesign.Models;
using vadoc_public_website_redesign.Crm;
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using System.Configuration;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Client;
using Microsoft.Crm.Sdk.Messages;
using System.Net;
using System.ServiceModel.Description;

namespace vadoc_public_website_redesign.Controllers
{
    public class ContactUsSurfaceController : SurfaceController
    {
        private readonly string _crmServiceAccountUserName =
            ConfigurationManager.AppSettings["CrmServiceAccountUserName"];
        private readonly string _crmServiceAccountPassword =
            ConfigurationManager.AppSettings["CrmServiceAccountPassword"];
        private readonly string _crmServiceAccountUrl =
            ConfigurationManager.AppSettings["CrmServiceUrl"];
        private const string Status = "statuscode";

        private DocServiceContext ServiceContext;

        // View path for contact partials
        public string GetViewPath(string name)
        {
            return $"/Views/Partials/ContactUs/{name}.cshtml";
        }
        // GET: Contact Us Form
        public ActionResult RenderContactForm()
        {
            return PartialView(GetViewPath("ContactUsForm"), new ContactUsFormModel());
        }

        private bool FindBestContact(Contact proposedContact, out Contact contact)
        {
            if (proposedContact == null)
            {
                contact = new Contact();
                return false;
            }

            var proposedContactLastName = proposedContact.LastName;
            var proposedEmail = proposedContact.EMailAddress1;

            var contacts = ServiceContext.ContactSet.Where(x =>
                x.LastName != null &&
                x.LastName == proposedContactLastName &&
                x.EMailAddress1 != null &&
                x.EMailAddress1 == proposedEmail);

            contact = contacts.Where(x => x.StateCode.Value == ContactState.Active).OrderByDescending(x => x.CreatedOn)
                .FirstOrDefault();

            if (contact != default(Contact)) return true;

            contact = contacts.Where(x => x.StateCode.Value == ContactState.Inactive)
                .OrderByDescending(x => x.CreatedOn).FirstOrDefault();

            if (contact != default(Contact)) return true;

            contact = proposedContact;

            return false;
        }

        // Submit Form
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SubmitContactForm(ContactUsFormModel model)
        {
            if(!TempData.ContainsKey("CustomErrors"))
            {
                TempData.Add("CustomErrors", new List<string>());
            } 
            
            if (!ModelState.IsValid)
            {
                ((List<string>)TempData["CustomErrors"]).Add("Please Fix the following form errors.");
                TempData["JsDisabled"] = true;
                TempData["FormSuccess"] = false;
                TempData["InvalidModel"] = true;

                return CurrentUmbracoPage();
            }

            string message;
            try
            {
                ClientCredentials clientCredentials = new ClientCredentials();
                clientCredentials.UserName.UserName = _crmServiceAccountUserName;
                clientCredentials.UserName.Password = _crmServiceAccountPassword;

                // For Dynamics 365 Customer Engagement V9.X, set Security Protocol as TLS12
                ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
                var organizationServiceProxy =
                new OrganizationServiceProxy(new Uri(_crmServiceAccountUrl), null,
                    clientCredentials, null);
                organizationServiceProxy.EnableProxyTypes();

                ServiceContext = new DocServiceContext(organizationServiceProxy);

                if (organizationServiceProxy != null)
                {
                    Guid userid = ((WhoAmIResponse)organizationServiceProxy.Execute(new WhoAmIRequest())).UserId;

                    if (userid != Guid.Empty)
                    {
                        message = "Connection Established Successfully...";
                        TempData["Message"] = message;
                        TempData["Guid"] = userid;
                    }
                }
                else
                {
                    ((List<string>)TempData["CustomErrors"]).Add("Failed to establish connection");
                }
            }
            catch (Exception ex)
            {
                ((List<string>)TempData["CustomErrors"]).Add("Failed to establish connection");
            }

            var contact = new Contact { LastName = model.LastName.Trim(), EMailAddress1 = model.Email.Trim() };
            var foundContact = FindBestContact(contact, out contact);

            if (foundContact)
            {
                TempData["FoundContact"] = true;
                ServiceContext.UpdateObject(contact);
            }
            else
            {
                TempData["FoundContact"] = true;
                ServiceContext.AddObject(contact);
            }

            contact.FirstName = model.FirstName;

            var telephone = model.Telephone ?? string.Empty;
            telephone = new string(telephone.Where(char.IsDigit).ToArray());
            if (!string.IsNullOrEmpty(telephone))
            {
                contact.Telephone1 =
                    $"({telephone.Substring(0, 3)}) {telephone.Substring(3, 3)}-{telephone.Substring(6, 4)}";
                contact.crspnd_BusinessExtension = telephone.Length > 10 ? telephone.Substring(10) : null;
            }

            if (!string.IsNullOrEmpty(model.AddressLine1) || !string.IsNullOrEmpty(model.AddressLine2) ||
                !string.IsNullOrEmpty(model.AddressCity) || !string.IsNullOrEmpty(model.PostalCode))
            {
                contact.Address1_Line1 = null;
                contact.Address1_Line2 = null;
                contact.Address1_City = null;
                contact.Address1_StateOrProvince = null;
                contact.Address1_PostalCode = null;

                if (!string.IsNullOrEmpty(model.AddressLine1))
                    contact.Address1_Line1 = model.AddressLine1;

                if (!string.IsNullOrEmpty(model.AddressLine2))
                    contact.Address1_Line2 = model.AddressLine2;

                if (!string.IsNullOrEmpty(model.AddressCity))
                    contact.Address1_City = model.AddressCity;

                contact.Address1_StateOrProvince = model.AddressState;

                if (!string.IsNullOrEmpty(model.PostalCode))
                    contact.Address1_PostalCode = model.PostalCode;
            }

            var emailContent = new Incident
            {
                crspnd_IPAddress = Request.UserHostAddress,
                crspnd_MessageFormat = new OptionSetValue(675580005),
                crspnd_PortalSubject = model.Subject,
                crspnd_OriginalTopic = new EntityReference(Topic.EntityLogicalName, Guid.Parse("ecdce284-3fe1-e811-a956-001dd800c973")),
                crspnd_ReceivedDate = DateTime.SpecifyKind(DateTime.Now, DateTimeKind.Utc),
                crspnd_ResponseRequested = true,
                crspnd_Title = model.Subject,
                crspnd_Topic = new EntityReference(Topic.EntityLogicalName, Guid.Parse("ecdce284-3fe1-e811-a956-001dd800c973")),
                Description = model.Message,
                OwnerId = ServiceContext.ssc_controlpanelSet.FirstOrDefault()?.crspnd_DefaultCaseOwner
            };

            try
            {
                // ReSharper disable once RedundantAssignment
                var crmResult = ServiceContext.SaveChanges();

                // relate this incident to the contact
                emailContent.CustomerId = contact.ToEntityReference();

                ServiceContext.AddObject(emailContent);

                crmResult = ServiceContext.SaveChanges();

                if (foundContact && contact.StateCode.Value == ContactState.Inactive)
                {
                    var setStateRequest = new SetStateRequest
                    {
                        EntityMoniker = new EntityReference { Id = contact.Id, LogicalName = contact.LogicalName },
                        State = new OptionSetValue(0), // 0 = active, 1 = inactive
                        Status = new OptionSetValue(1) // 1 = active, 2 = inactive
                    };

                    ServiceContext.Execute(setStateRequest);
                }

                if (!crmResult.HasError)
                {
                    TempData["FormSuccess"] = true;
                    ModelState.Clear();
                    if (Request.IsAjaxRequest())
                    {
                        return PartialView(GetViewPath("ContactUsSuccess"));
                    }

                    TempData["JsDisabled"] = true;
                    return CurrentUmbracoPage();
                }
                else
                {
                    TempData["FormSuccess"] = false;
                    if (Request.IsAjaxRequest())
                    {
                        return PartialView(GetViewPath("ContactUsError"));
                    }

                    TempData["JsDisabled"] = true;
                    return CurrentUmbracoPage();
                }
            }
            catch (Exception ex)
            {
                message = "Exception caught - " + ex.Message;
                ((List<string>)TempData["CustomErrors"]).Add(message);
                TempData["FormSuccess"] = false;

                if(Request.IsAjaxRequest())
                {
                    return PartialView(GetViewPath("ContactUsError"));
                }

                TempData["JsDisabled"] = true;

vadoc-public-website-redesign/Controllers/JobsDataSurfaceController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using vadoc_public_website_redesign.Models;

namespace vadoc_public_website_redesign.Controllers
{
    public class JobsDataSurfaceController : SurfaceController
    {
        private const string PARTIAL_VIEW_FOLDER = "~/Views/Partials/Jobs/";
        JobRepository JobRepo = new JobRepository();
        // GET: JobsDataSurface
        public ActionResult RenderJobsList()
        {

            List<Job> jobs = JobRepo.JobsList;
            TempData["JobsList"] = jobs;
            return PartialView($"{PARTIAL_VIEW_FOLDER}JobsList.cshtml", JobRepo);
        }
    }
}

vadoc-public-website-redesign/Controllers/PublicResourcesSurfaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using vadoc_public_website_redesign.Models;

namespace vadoc_public_website_redesign.Controllers
{
    public class PublicResourcesSurfaceController : SurfaceController
    {
        private const string MAIN_VIEW_FOLDER = "~/Views/";
        private const string PARTIAL_VIEW_FOLDER = "~/Views/Partials/OffenderLocator/";
        // GET: Offender Locator Page
        public ActionResult RenderOffenderLocatorPage()
        {
            return Redirect("/public-resources/offender-locator");
        }
        public ActionResult RenderOffenderLocatorForm()
        {
            return PartialView($"{PARTIAL_VIEW_FOLDER}OffenderLocatorForm.cshtml");
        }

        public ActionResult RenderOffenderSearchResults()
        {
            return PartialView($"{PARTIAL_VIEW_FOLDER}OffenderSearchResults.cshtml");
        }

        public ActionResult RenderOffenderSearchNoResults()
        {
            return PartialView($"{PARTIAL_VIEW_FOLDER}OffenderSearchNoResults.cshtml");
        }
    }
}

vadoc-public-website-redesign/Views/About.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
    Layout = "MasterLayout.cshtml";
}

@section HighPriorityStyles
    {
    <link href="~/styles/primary-page.css" rel="stylesheet" />
}
@Html.Partial("SiteLayout/BreadCrumbs")

<main>
    <section id="about-intro" class="content-wrapper">
        <div class="col-19">
            @CurrentPage.pageIntro
            <ul class="icon-list">
                <li>
                    <img class="li-icon" src="/images/modals/step-2.svg" aria-hidden="true" />
                    <div class="li-info col-17">
                        <h3>Mission</h3>

                        @CurrentPage.mission
                    </div>
                </li>
                <li>
                    <img class="li-icon" src="/images/modals/step-2.svg" aria-hidden="true" />
                    <div class="li-info col-17">
                        <h3>Values</h3>
                        @if (Model.Content.GetPropertyValue<string[]>("values").Length > 0)
                        {
                            <ul class="unstyled-list">
                                @foreach (var value in Model.Content.GetPropertyValue<string[]>("values"))
                                {
                                    <li>@value</li>
                                }
                            </ul>

                        }
                    </div>
                </li>
                <li>
                    <img class="li-icon" src="/images/modals/step-2.svg" aria-hidden="true" />
                    <div class="li-info col-17">
                        <h3>Vision</h3>
                        @CurrentPage.vision
                    </div>
                </li>
            </ul>
        </div>
    </section>
    <section id="executive-staff">
        <div class="content-wrapper">
            <div class="col-19">
                <h2>Executive Staff</h2>
                @if (CurrentPage.Children.Count() > 0)
                {
                    <ul id="executives">
                        @foreach (var executive in CurrentPage.Children)
                        {
                            <li class="feature">
                                <figure class="modal-trigger" data-id="111">
                                    <img src="@executive.headshot" alt="@executive.displayName">
                                </figure>
                                <div class="bio col-14">
                                    <h3>@executive.displayName,&nbsp;<span>@executive.title</span></h3>
                                    @executive.bio       
                                </div>
                            </li>
                        }
                    </ul>
                }
            </div>
        </div>
    </section>
</main>

vadoc-public-website-redesign/Views/Contact.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage

@{
    Layout = "MasterLayout.cshtml";
}

@section HighPriorityStyles
    {
    <link href="~/styles/primary-page.css" rel="stylesheet" />
}
@Html.Partial("SiteLayout/BreadCrumbs")
<!-- Begin Main Content -->
<main>
    <div class="left">
        <div id="contact-intro" class="description">
            <p id="mobile-page-heading" class="h1-style">@CurrentPage.pageTitle</p>
        </div>

        <div id="form-results">
            @if (TempData["JsDisabled"] != null && TempData["FormSuccess"] != null)
            {
                if ((bool)TempData["JsDisabled"] && (bool)TempData["FormSuccess"])
                {
                    @Html.Partial("ContactUs/ContactUsSuccess")
                }

                if ((bool)TempData["JsDisabled"] && !(bool)TempData["FormSuccess"])
                {
                    @Html.Partial("ContactUs/ContactUsError")
                }
            }
        </div>

        @{ Html.RenderAction("RenderContactForm", "ContactUsSurface");}
        @if (TempData["Message"] != null)
        {
            <h3>@TempData["Message"]</h3>
        }
    </div>
    <div class="right col-8">
        @Html.Partial("SiteLayout/SidebarContactCard")

        <ul id="contact-list">
            <li class="vcard">
                <h2 class="org">ADA</h2>
                <p>For questions and information regarding ADA requirements for offenders.</p>
                <div class="tel">
                    <p class="value">(804) 763-9960</p>
                </div>
                <a href="mailto:Barry.Marano@vadoc.virginia.gov" class="email">Barry.Marano@vadoc.virginia.gov</a>
            </li>
            <li class="vcard">
                <h2 class="org">Classification</h2>
                <div class="tel">
                    <p class="value">(804) 674-3131</p>
                </div>
            </li>
            <li class="vcard">
                <h2 class="org">Health &amp; Medical</h2>
                <p>For questions regarding health and medical concerns at VADOC facilities (not local jails. We will review the concern with the facility staff and send a written response to the named offender.</p>
                <div class="tel">
                    <p class="value">123-456-7890</p>
                </div>
                <a href="mailto:dochealthservicescomplaints@vadoc.virginia.gov" class="email">dochealthservicescomplaints@vadoc.virginia.gov</a>
            </li>
            <li class="vcard">
                <h2 class="org">Human Resources</h2>
                <p>For inquiries and assistance on job applications and other HR-related matters.</p>
                <div class="tel">
                    <p class="value">804-674-3507</p>
                </div>
                <h3>Job Openings</h3>
                <a href="mailto:Recruitment@vadoc.virginia.gov" class="email">Recruitment@vadoc.virginia.gov</a>

                <h3>Employment Verifications</h3>
                <a href="mailto:DOCVerifications@vadoc.virginia.gov" class="email">DOCVerifications@vadoc.virginia.gov</a>
            </li>
            <li class="vcard">
                <h2 class="org">PREA</h2>
                <p>If you were, or someone you know was, sexually abused or sexually harassed while in custody or under the supervision of the VADOC, please call the confidential reporting hotline. We will ensure that all staff, contractors, volunteers, offenders, and probationers are free from retaliation for reporting occurrences of sexual abuse or sexual harassment.</p>
                <div class="tel">
                    <p class="body-bold">Confidential Reporting Hotline</p>
                    <p class="value">1 (855) 602-7001</p>
                    <p class="body-bold">General Phone</p>
                    <p class="value">(804) 887-7921</p>
                </div>
                <a href="mailto:PREAGrievance@vadoc.virginia.gov" class="email">PREAGrievance@vadoc.virginia.gov</a>
            </li>
            <li class="vcard">
                <h2 class="org">Visitation</h2>
                <p>For inquiries regarding visitation policies and procedures.</p>
                <div class="tel">
                    <p class="value">(804) 887-8341</p>
                </div>
                <a href="mailto:visitationinquiries@vadoc.virginia.gov" class="email"> visitationinquiries@vadoc.virginia.gov</a>
            </li>
            <li class="vcard">
                <h2 class="org">Website Technology</h2>
                <p>For inquiries or feedback on the VADOC website and its technology, contact the webmaster.</p>
                <div class="tel">
                    <p class="value">123-456-7890</p>
                </div>
                <a href="mailto:webmaster@vadoc.virginia.gov" class="email">webmaster@vadoc.virginia.gov</a>
            </li>
        </ul>
    </div>
</main>
<!-- End Main Content -->
<!-- Loading Indicator -->
@Html.Partial("SiteLayout/LoadingIndicator")
@section ScriptsBottom
{
    <script src="~/scripts/contact-form.js"></script>
}

vadoc-public-website-redesign/Views/JobOpportunities.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
    Layout = "MasterLayout.cshtml";
}
@section HighPriorityStyles
    {
    <link href="~/styles/primary-page.css" rel="stylesheet" />
    <link href="~/styles/public-resources.css" rel="stylesheet" />
}
@Html.Partial("SiteLayout/BreadCrumbs")
<!-- Begin Main Content -->
<main>
    <!-- Begin Current Job Openings -->
    <section id="current-job-openings" class="content-wrapper clear-fix">
        <div id="job-openings-intro" class="col-14">
            <p id="mobile-page-heading" class="h1-style">@CurrentPage.pageTitle</p>
            <div class="description">
                <p>The Virginia Department of Corrections (VADOC) is composed of more than 12,000 employees across the state. Every day, they provide exemplary services and programs for the rehabilitation and supervision of offenders in our care. Each member of the agency contributes to our mission of ensuring the safety and security of the Commonwealth.</p>
            </div>
        </div>
        <div id="call-to-apply" class="dark-background col-9">
            <div class="col-6">
                <h2 class="h1-style">How to Apply</h2>
                <p>Visit the <a href="http://jobs.virginia.gov/" target="_blank"> Department of Human Resources <img src="~/images/global/icons/external-link.svg" /></a> to learn more.</p>

            </div>
            <img src="/images/job-opportunities/how-to-apply.svg" aria-hidden="true">
        </div>
        <!-- Begin Featured Job Opennings -->
        <ul id="featured-jobs-list">
            <li class="jc-with-image col-14 mar-r-1">
                <figure class="image-link">
                    <a href="#">
                        <img src="/images/global/stock-images/typing.jpg" alt="A nerd typing">
                    </a>
                </figure>
                <div class="job-card-small">
                    <dl class="col-9">
                        <dt class="accessibility-hidden">Job Title</dt>
                        <dd class="hyperlink-heading h2-style">
                            <a href="#">Electronic Technician Senior</a>
                        </dd>
                        <dt class="accessibility-hidden">Job Description</dt>
                        <dd class="job-description"> Assists in the up-keep of the physical plant by testing, maintaining, inventory, installing and repairing...</dd>
                        <dt class="accessibility-hidden">Job Salary Range</dt>
                        <dd class="salary-range">$36,730 &ndash; $71,467</dd>
                        <dt class="accessibility-hidden">Job Location</dt>
                        <dd class="job-location">
                            <a class="unstyled-link" href="#">
                                <img class="inline-pin" src="/images/global/icons/location.svg" aria-hidden="true" /><span class="job-location-name">Greensville </span><span>Greensville, Virginia</span>
                            </a>
                        </dd>
                    </dl>

                    <img class="card-icon" src="/images/job-opportunities/job-category-icons/trades.svg" aria-hidden="true" />
                </div>
            </li>
            <li class="jc-with-image col-14">
                <figure class="image-link">
                    <a href="#">
                        <img src="/images/facilities-and-offices/atmore.jpg" alt="back yard">
                    </a>
                </figure>
                <div class="job-card-small">
                    <dl class="col-9">
                        <dt class="accessibility-hidden">Job Title</dt>
                        <dd class="hyperlink-heading h2-style">
                            <a href="#">Food Operations Director</a>
                        </dd>
                        <dt class="accessibility-hidden">Job Description</dt>
                        <dd class="job-description">Directs a comprehensive food service program for the Department of Corrections Headquarters Café. Supervises staff and offenders in...</dd>
                        <dt class="accessibility-hidden">Job Salary Range</dt>
                        <dd class="salary-range">$43,892 &ndash; $83,201</dd>
                        <dt class="accessibility-hidden">Job Location</dt>
                        <dd class="job-location">
                            <a class="unstyled-link" href="#">
                                <img class="inline-pin" src="/images/global/icons/location.svg" aria-hidden="true" /><span class="job-location-name">VADOC Headquarters</span><span>Richmond, Virginia</span>
                            </a>
                        </dd>
                    </dl>

                    <img class="card-icon" src="/images/job-opportunities/job-category-icons/food-services.svg" aria-hidden="true" />
                </div>
            </li>
        </ul>
        <!-- End Featured Job Opennings -->
        <!-- Begin Job Sort UI Buttons -->
        <div id="results-sort" class="button-group" aria-hidden="true">
            <p class="button-group-title">Sort by: </p>
            <ul>
                <li>
                    <button id="name-sort"><span class="accessibility-hidden">Sort results by</span>Name</button>
                </li>
                <li>
                    <button id="location-sort"><span class="accessibility-hidden">Sort results by</span>Location</button>
                </li>
                <li>
                    <button id="salary-sort"><span class="accessibility-hidden">Sort results by</span>Salary Range</button>
                </li>
                <li>
                    <button id="date-sort"><span class="accessibility-hidden">Sort results by</span>Close Date</button>
                </li>
            </ul>
        </div>
        <!-- End Job Sort UI Buttons -->
        <!-- Begin Sortable Job Openings List -->
        @{Html.RenderAction("RenderJobsList", "JobsDataSurface"); }

    </section>
    <!-- End Current Job Openings -->
    <!-- Begin Employee Benefits -->
    <section id="employee-benefits">
        <div class="content-wrapper clear-fix">
            <h2>Employee Benefits</h2>
            <div class="description col-14">
                <p>VADOC employees enjoy a number of generous benefits, including:</p>
            </div>
            <ul class="clear-fix">
                <li>
                    <figure class="benefit">
                        <img src="/images/job-opportunities/benefit-icons/calendar.svg" aria-hidden="true">
                        <figcaption>12 Paid Holidays</figcaption>
                    </figure>
                </li>
                <li>
                    <figure class="benefit">
                        <img src="/images/job-opportunities/benefit-icons/retirement.svg" aria-hidden="true">
                        <figcaption>Retirement Savings Program</figcaption>
                    </figure>
                </li>
                <li>
                    <figure class="benefit">
                        <img src="/images/job-opportunities/benefit-icons/disability.svg" aria-hidden="true">
                        <figcaption>Long &amp; Short-term Disability</figcaption>
                    </figure>
                </li>
                <li>
                    <figure class="benefit">
                        <img src="/images/job-opportunities/benefit-icons/education.svg" aria-hidden="true">
                        <figcaption>Education Assistance</figcaption>
                    </figure>
                </li>
                <li>
                    <figure class="benefit">
                        <img src="/images/job-opportunities/benefit-icons/employee-assistance.svg" aria-hidden="true">
                        <figcaption>Employee Assistance Program</figcaption>
                    </figure>
                </li>
                <li>
                    <figure class="benefit">
                        <img src="/images/job-opportunities/benefit-icons/flex.svg" aria-hidden="true">
                        <figcaption>Flexible Spending Program</figcaption>
                    </figure>
                </li>
            </ul>
            <a href="#" class="primary-button">See All Employee Benefits</a>
        </div>
    </section>
    <!-- End Employee Benefits -->
</main>
<!-- End Main Content -->
@section ScriptsBottom
    {
    <script src="~/scripts/job-cards.js"></script>
}

vadoc-public-website-redesign/Views/OffenderLocator.cshtml
@inherits UmbracoTemplatePage
@using ContentModels = Umbraco.Web.PublishedContentModels;

@{
    Layout = "MasterLayout.cshtml";
}

@section LowPriorityStyles
    {
    <link rel="stylesheet" href="~/styles/jquery-ui-datepicker.min.css" />
}

@section HighPriorityStyles
    {
    <link rel="stylesheet" href="~/styles/public-resources.css" />
}

@Html.Partial("SiteLayout/BreadCrumbs")
<!-- Begin Main Content -->
<main id="main-content">
    <p id="mobile-page-heading" class="h1-style">@CurrentPage.pageTitle"</p>

    <div id="form-requirements" class="content-wrapper">
        <p>A first or last name OR Offender I.D. # are required for all searches.</p>
    </div>

    <section id="offender-search">
        <!-- Begin Offender Locator Form -->
        @{ Html.RenderAction("RenderOffenderLocatorForm", "PublicResourcesSurface");}
        <!-- End Offender Locator Form -->


    </section>
</main>
<!-- End Main Content -->
@section ScriptsBottom
    {
    <script src="~/scripts/offender-locator.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/3.0.4/fuse.min.js"></script>
}

vadoc-public-website-redesign/Views/SearchResults.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
    Layout = "MasterLayout.cshtml";
}


@section HighPriorityStyles
    {
    <link href="~/styles/primary-page.css" rel="stylesheet" />
}

@Html.Partial("SiteLayout/BreadCrumbs")
<!-- Begin Main Content -->
<main class="content-wrapper">
    <section id="site-search" class="col-19">
        @CurrentPage.bodyText
    </section>
</main>
<!-- End Main Content -->

vadoc-public-website-redesign/Views/VisitationForm.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
    Layout = "MasterLayout.cshtml";
}

@section HighPriorityStyles
    {
    <link href="/static/css/main.8b7fb58b.css" rel="stylesheet" />
    <link href="~/styles/visitation-form.css" rel="stylesheet" />
}

@Html.Partial("SiteLayout/BreadCrumbs")

@Html.Partial("VisitationApplication/index")